### ISSUE TITLE
About 3d Size

### ISSUE THREAD

**Issue by MENG1996** [LIVIAETS/SizeLoss_WSS#5]
Thanks for your work.I would like to ask a detailed question. Does the 3d size segmentation in the article also use a 2d network? and each batch contains all slices of 3d volume？

**Comment by HKervadec** [comment]
Yes exactly, I kept the same 2D network and fed all slices for a single patient at once (on ACDC this was around 10/15 images at a time).

The only difference, then is when computing the size: one does not compute 15 independent sizes (one per images), but one for the whole volume. This difference [can be seen here](https://github.com/LIVIAETS/SizeLoss_WSS/blob/master/utils.py#L70), with only the `c` axis remains in the einsum:
```python
# fns
def soft_size(a: Tensor) -> Tensor:
    return torch.einsum("bcwh->bc", a)[..., None]


def batch_soft_size(a: Tensor) -> Tensor:
    return torch.einsum("bcwh->c", a)[..., None]
```

**Comment by MENG1996** [comment]
Thank you for your reply
